import type { Metadata } from 'next'

import './globals.scss'
import { AntdRegistry } from '@ant-design/nextjs-registry'
import { ConfigProvider } from 'antd'
import { theme } from '@/core/configs/theme/theme'
import { Poppins } from 'next/font/google'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const poppins = Poppins({ weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'], subsets: ['latin'] })

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>): React.ReactElement {
  return (
    <html lang='en'>
      <AntdRegistry>
        <ConfigProvider theme={theme}>
          <body className={poppins.className}>{children}</body>
        </ConfigProvider>
      </AntdRegistry>
    </html>
  )
}
